name: Build and run

on: push

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install extra packages
        run: |
          sudo apt-get install -y qemu-system-arm
      - name: Install ARM toolchain
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-elf.tar.xz
          tar xvaf *.tar.xz
          echo "$PWD/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-elf/bin/" >> "$GITHUB_PATH"
      - name: Install kraft
        run: |
          mkdir -p bin
          cd bin
          wget https://github.com/unikraft/kraftkit/releases/download/v0.9.2/kraft_0.9.2_linux_amd64.tar.gz
          tar xvaf *.tar.gz
          rm *.tar.gz
          echo "$PWD" >> "$GITHUB_PATH"
      - name: Build
        run: |
          kraft build
      - name: Display the configuration
        run: |
          cat .config.simple_qemu-arm64
      - name: Run
        run: |
          qemu-system-aarch64 -machine virt -cpu cortex-a53 -nographic -nodefaults -serial stdio -netdev user,id=n0,restrict=on -device virtio-net-pci,netdev=n0 -kernel .unikraft/build/simple_qemu-arm64
